### ISSUE TITLE
ATAC_find_active_promoter

### ISSUE THREAD

**Issue by wherrylab** [kaizhang/Taiji#7]
Hi Kai,
Can you give more details for identifying active promoters in this step of the pipeline -ATAC_find_active_promoter ?

Thank you

**Comment by kaizhang** [comment]
Promoters are defined by upstream 5000 bp plus downstream 1000 bp of genes' TSSs.
Promoters are active if they overlap with open chromatin (ATAC-seq peaks).
The purpose of this step is to filter out inactive promoters so that distal ATAC-seq peaks, considered as enhancers, will not be assigned to them.

**Comment by wherrylab** [comment]
Thank you,that is helpful.
